name: Tests

on:
  # This avoids having duplicate builds for a pull request
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  smoke:
    name: Linux smoke test Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      QT_DEBUG_PLUGINS: 1
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/install.txt
      - name: Install Test Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/dev.txt
      - name: Install Package
        shell: bash -l {0}
        run: python setup.py develop
      - name: Show Environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum pytest tests --cov=qtsass --cov-report=term-missing -x -vv

  linux:
    name: Linux Py${{ matrix.PYTHON_VERSION }}
    needs: smoke
    runs-on: ubuntu-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      QT_DEBUG_PLUGINS: 1
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/install.txt
      - name: Install Test Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/dev.txt
      - name: Install Package
        shell: bash -l {0}
        run: python setup.py develop
      - name: Show Environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum pytest tests --cov=qtsass --cov-report=term-missing -x -vv

  macos:
    name: Mac Py${{ matrix.PYTHON_VERSION }}
    needs: smoke
    runs-on: macos-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      QT_DEBUG_PLUGINS: 1
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/install.txt
      - name: Install Test Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/dev.txt
      - name: Install Package
        shell: bash -l {0}
        run: python setup.py develop
      - name: Show Environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: pytest tests --cov=qtsass --cov-report=term-missing -x -vv

  windows:
    name: Windows Py${{ matrix.PYTHON_VERSION }}
    needs: smoke
    runs-on: windows-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      QT_DEBUG_PLUGINS: 1
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/install.txt
      - name: Install Test Dependencies
        shell: bash -l {0}
        run: pip install -r requirements/dev.txt
      - name: Install Package
        shell: bash -l {0}
        run: python setup.py develop
      - name: Show Environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: pytest tests --cov=qtsass --cov-report=term-missing -x -vv
